### ISSUE TITLE
未开通联通iptv能否使用列表观看

### ISSUE THREAD

**Issue by lee2333** [gabacai/tj-unicom-iptv#4]
请问天津联通用户，如果没有开通iptv服务是否可以用这个列表来观看呢

**Comment by lee2333** [comment]
而且是不是需要进入光猫后台调整参数

**Comment by gabacai** [comment]
我家二宽带.从未开通iptv.是可以看的.
如果不可以.
1是看光猫配置.2.如果光猫配置没有问题.可能联通那边限制了.

**Comment by lee2333** [comment]
感谢作者，已经借用抓去的列表成功观看了
